apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: newsbiasdetector
  namespace: '96460072068'
  selfLink: >-
    /apis/serving.knative.dev/v1/namespaces/96460072068/services/newsbiasdetector
  uid: 14028aad-e692-4c74-9693-e160d1ebe626
  resourceVersion: AAYu2dhHLAs
  generation: 3
  creationTimestamp: '2025-02-24T02:04:10.908078Z'
  labels:
    commit-sha: 1824e6f5667943917397a608b1e5f3243c642690
    gcb-build-id: 3f372729-9f68-42a6-8ed5-6c43bc23f35e
    gcb-trigger-id: 78971428-6ea5-4769-975e-c62290038298
    gcb-trigger-region: global
    managed-by: gcp-cloud-build-deploy-cloud-run
    cloud.googleapis.com/location: us-central1
  annotations:
    serving.knative.dev/creator: jimmymoonstation@gmail.com
    serving.knative.dev/lastModifier: 96460072068-compute@developer.gserviceaccount.com
    run.googleapis.com/client-name: gcloud
    run.googleapis.com/client-version: 511.0.0
    run.googleapis.com/operation-id: a017888e-1db7-485f-b474-1d7d91853ca8
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/urls: >-
      ["https://newsbiasdetector-96460072068.us-central1.run.app","https://newsbiasdetector-nnhvksslxa-uc.a.run.app"]
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: jqzlhyhlhu
        commit-sha: 1824e6f5667943917397a608b1e5f3243c642690
        gcb-build-id: 3f372729-9f68-42a6-8ed5-6c43bc23f35e
        gcb-trigger-id: 78971428-6ea5-4769-975e-c62290038298
        gcb-trigger-region: global
        managed-by: gcp-cloud-build-deploy-cloud-run
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: gcloud
        run.googleapis.com/client-version: 511.0.0
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 96460072068-compute@developer.gserviceaccount.com
      containers:
        - name: placeholder-1
          image: >-
            us-central1-docker.pkg.dev/newsbias-438816/cloud-run-source-deploy/newsbiasdetector/newsbiasdetector:1824e6f5667943917397a608b1e5f3243c642690
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 8080
  traffic:
    - percent: 100
      latestRevision: true
